### ISSUE TITLE
NewRelic NodeJS Agent's Winston instrumentation causes ALL logs to be JSON

### ISSUE THREAD

**Issue by fourpastmidnight** [newrelic/node-newrelic#1208]
## Description

I recently added the Node JS agent to my Node JS application. I have logging enabled via Winston v3.3.3 in my application.

My logging setup is that I have up to three log sinks/transports:

1. A console logger, which can be disabled by setting the environment variable `MY_APP_NO_CONSOLE_LOGGING` (where `MY_APP_` in reality is the name of my application)
2. A file logger that logs plain-text log files for easy reading
3. A file logger that logs in JSON so I can use PowerShell or other tools to "query" logs.

However, after enabling the New Relic Node JS agent's logging in context feature via setting `NEW_RELIC_APPLICATION_LOGGING_ENABLED=true`, now _ALL_ transports/sinks end up logging in JSON format. Your logger interceptor **SHOULD NOT** change the user-defined log output for existing transports/sinks.

> **Note**
>
> Throughout this issue, I may interchangeably use transport and sink. Serilog has sinks, other loggers have transports&mdash;they're the same thing.

## Expected Behavior

I expected that the agent would simply _intercept_ the logging calls and work on a copy of the logging data to send to New Relic, leaving the final log output alone.

Instead, you should either:

* _**Only**_ intercept logging calls and mutate a _**copy**_ of the log data and send the mutated copy to New Relic, forwarding the original log data through the winston logging pipeline, or...
* instead of modifying the existing logger format, add yourself as an additional transport/sink within Winston, perhaps using one of their a Stream, HTTP, or your own Custom transport/sink, configuring the format for this additional transport/sink. The `winston-transport` API is fairly simple, so a custom transport shouldn't be too hard to implement.

Regarding my second option of adding your own transport, it should be noted that Winston has some nasty behavior of potentially mutating the info object as the log entry is processed for sending to a transport. Particularly, if you have more than one transport. And particularly if you are using the splat formatter and you assign different formatters to different transports. This is because winston is bad about making sure that in all formatters that it works on a _copy_ of the log data instead of the actual log data object itself.

So, to insulate from that, New Relic should probably insert itself as the _first_ transport, if possible. I've had to resort to other drastic measures in my particular setup, such as rewriting their splat formatter so it "does the right thing"<sup>TM</sup>, as well as make sure any custom formatters I create work on a _deep clone_ of the `info` object and mutate the clone (using the `deepclone` npm library).

## Steps to Reproduce

Here's how to reproduce today's behavior.

First, here's my winston logger initializer, in `logging.ts`, which is imported in my application's composition root:

```ts
import jsonStringify from 'safe-stable-stringify';
import { SPLAT } from 'triple-beam'; // This is a winston "component"...
import {
  Logform,
  Logger,
  LoggerOptions,
  config as Config,
  createLogger,
  format,
  transports as Transports
} from 'winston';
import TransportStream from 'winston-transport';
// These imports are all the custom formatters I created
// In particular, the splatMessage formatter fixes issues with Winston's
// built-in splat formatter.
//import {
//  SysLogLevel as LogLevel,
//  LogLevelCasingStyle,
//  LogLevelFormatterOptions,
//  LogLevelPaddingStyle,
//  formatLogLevel,
//  enrichWithCorrelationId,
//  redactLogEntries,
//  splatMessage
//} from '@my-app/logging';

export const initializeLogger = () : Logger => {
  let baseLogLevel: LogLevel = process.env.NODE_ENV === 'development' ? LogLevel.Info : LogLevel.Notice;
  let logToConsole = true;
  let logToFile = true;
  let colorizeConsoleLogs = true;
  let consoleLogLevel: LogLevel = baseLogLevel;
  let fileLogLevel: LogLevel = baseLogLevel;
  let logSinks: TransportStream[] = [];

  const parseLogLevel = (s: string): LogLevel => {
    // Code in here returns an expected log level string for configuring the logger...
    // no need to bother with the actual implementation...
    return s as LogLevel;
  }

  const falseRegex = /^(0|false|no)$/i;
  if (!(process.env.MY_APP_LOG_NO_CONSOLE ?? 'false').match(falseRegex)?.length) {
    logToConsole = false;
  }

  if (!(process.env.MY_APP_LOG_NO_FILE ?? 'false').match(falseRegex)?.length) {
    logToFile = false;
  }

  if (logToConsole && !(process.env.MY_APP_LOG_CONSOLE_NO_COLOR ?? 'false').match(falseRegex)?.length) {
    colorizeConsoleLogs = false;
  }

  if (process.env.MY_APP_LOG_LEVEL) {
    baseLogLevel = parseLogLevel(process.env.MY_APP_LOG_LEVEL);
  }

  if (process.env.MY_APP_LOG_CONSOLE_LEVEL) {
    consoleLogLevel = parseLogLevel(process.env.MY_APP_LOG_CONSOLE_LEVEL);
  }

  if (process.env.MY_APP_LOG_FILE_BASE_FILENAME && process.env.MY_APP_LOG_FILE_LEVEL) {
    fileLogLevel = parseLogLevel(process.env.MY_APP_LOG_FILE_LEVEL);
  }

  // Log entry redacters to redact sensitive information contained in log entries, such as API keys
  //const logEntryRedacters = [ /* ... */ ];

  // ***********************************************************************************
  // *    ***** ****     I    M    P    O    R    T    A    N    T    ****    *****    *
  // ***********************************************************************************
  // ! format.combine creates a "pipeline" of formatters.
  // ! I.e., when adding a formatter to the pipeline, each one is applied, in order,
  // ! to the `info` object. So ordering is IMPORTANT when creating the base logger
  // ! formatter and subsequent transport formatters.
  // ! Also be aware that some formatters MUTATE the `info` object, causing subsequent
  // ! transports to not get the same data as was present on the original, unmutated
  // ! `info` object.
  // ! All formatters created for this app ensure that they operate on a clone of the
  // ! `info` object so that each transport gets the ORIGINAL log data as it came into
  // ! the logging pipeline so that, for each transport, the data can be formatted as
  // ! desired.

  // A custom formatter that prints plain-text log files where each entry has the format:
  //   [2021-08-07T18:35:01.159-0400] [INFO   ] [ApiLocation    ] The loge message { extra: "Other data" }
  const StandardUnstructuredFormat = format.printf(((info: Logform.TransformableInfo) => {
    const { timestamp, level, message, location, ...rest } = info;
    return `[${timestamp}] [${level}] ${location ? `[${(location as string).padEnd('LongestLengthLocation'.length)}] ` : ''}${message}${!(!!rest && Object.keys(rest).length === 0 && rest.constructor === Object) ? ' ' + jsonStringify(rest) : ''}`
  }));

  const loggerOptions: LoggerOptions = {
    exitOnError:  false,

    // This is a "base" log formatter. It gets
    // `format.combine()`ed with specified transport formatters,
    // if any, and runs BEFORE any other formatters defined on
    // transports.
    format: format.combine(
      // code not shown for my custom reaction formatter
      //redactLogEntries({ redacters: logEntryRedacters }),
      // I created my own custom splat formatter because winston's mutates `info` :(...
      //splatMessage,
      format.timestamp({ format: 'YYYY-MM-DD HH:mm:ss.SSSZZ' } as Logform.TimestampOptions)
    ),
    levels: Config.syslog.levels
  };

  // Here, I setup my log transports
  if (logToFile) {
    logSinks = [
      ...logSinks,
      new Transports.File({
        dirname: `${process.env.MY_APP_LOG_FILE_DIR ?? '.'}`,
        filename: `${process.env.MY_APP_LOG_FILE_BASE_FILENAME ?? 'my-app'}.log.json`,
        // REMEMBER: formatters listed here get COMBINED with the "base" formatters set
        //           on the logging instance itself!
        format: format.json(),
        level: fileLogLevel
      }),
      new Transports.File({
        dirname: `${process.env.MY_APP_LOG_FILE_DIR ?? '.'}`,
        filename: `${process.env.MY_APP_LOG_FILE_BASE_FILENAME ?? 'my-app'}.log`,
        // REMEMBER: formatters listed here get COMBINED with the "base" formatters set
        //           on the logging instance itself!
        format: format.combine(
          // My custom log level formatter...
          //formatLogLevel(...),
          // An enriched that adds a correlation ID to the log entries so
          // I can trace related entries
          //enrichWithCorrelationId(),
          // finally, ensure the entry is formatted as plain-text with a particular format
          StandardUnstructuredFormat
        ),
        level: fileLogLevel
      })
    ]
  }

  if (logToConsole) {
    logSinks = [
      ...logSinks,
      new Transports.Console({
        // REMEMBER: formatters listed here get COMBINED with the "base" formatters set
        //           on the logging instance itself!
        format: format.combine({
          // A custom sensitive entry formatter
          //skipSensitiveEntries(),
          // A custom log level formatter
          //formatLogLevel(...),
          // correlation Id enricher...
          //enrichWithCorrelationId(),
          // Once again, use the standard unstructured format in the console
          // for easy reading
          StandardUnstructuredFormat
        ),
        level: consoleLogLevel
      })
    ]
  }

  // Now add the log sinks/transports to the logger options
  loggerOptions.transports = logSinks;

  // and create the logger
  return createLogger(loggerOPtions);
}

export default initializeLogger;
```

Next, in my application's composition root, `index.ts`:

```ts
import dotEnvExpand from 'dotenv-expand';
import dotEnvFlow from 'dotenv-flow';
import initializeLogger from './logging';
import setupApp from './app';

// Setup the environment by reading the environment variables and any specified .env.* files.
dotEnvExpand(dotEnvFlow.config());

// Some other basic app initialization happens here, such as the expected URL and port
// that Express will listen on...
const baseAppUrl = `${process.env.MY_APP_SCHEME}://${process.env.MY_APP_HOSTNAME}`;
const port = process.env.MY_APP_API_PORT || process.env.PORT;
const generateAppUrl = (port?: string) => `${baseAppUrl}:${tryConvertEnvVarToNumber(port, 5000)}`.replace(/.*:$/, '');

// This initializes the logger using the initializer above.
// New Relic stomps all over my logger configuration! :(
// If I ONLY wanted to send logs to New Relic, that'd be one thing.
// But in this early stage of "getting to know you", I want to continue
// to log to file and/or console.
//
// Also, for development purposes, I don't want to log to New Relic
// (easily accomplished by configuring the environment variables), but
// do want to log to console (and/or file).
const logger = initilaizeLogger().child({location: "MyApp"});

cost app = setupApp(/* Application configuration goes here */);
app.listen(port, () => {
  console.log('Starting MyApp...\n')

  try {
    logger.info('Application starting...');
    logEnvironmentConfiguration(process.env);
    logger.info(`Running in '${process.env.NODE_ENV?.toUpperCase()}' mode.`);
    logger.info('Application started.');
    logger.info(`Listening on ${generateAppUrl(port)}.`);
  } catch (error) {
    logger.error('An error occurred while starting MyApp.', { error });
    process.abort();
  }
});

function logEnvironmentConfiguration(env: NodeJS.ProcessEnv): void {
  logger.info("The current application configuration is:")

  let maxKeyLength = 0;
 // Yes, there's probably a better way to do this...
  for (let key in env) {
    if (key.match(/^(MY_APP_|NEW_RELIC_|NODE_ENV|PORT)/)?.length) {
      maxKeyLength = maxKeyLength < key.length ? key.length : maxKeyLength
    }
  }

  logger.info('  NAME'.padEnd(maxKeyLength+2) + '    VALUE');
  logger.info('  ----'.padEnd(maxKeyLength+2) + '    -----');

  for (let key in env) {
    if (key.match(/^(MY_APP_|NEW_RELIC_|NODE_ENV|PORT)/)?.length) {
      logger.info(`  ${key.padEnd(maxKeyLength)}    ${env[key]}`);
    }
  }
}

function tryConvertEnvVarToNumber(s? : string | number, def?: number): number {
  try {
    return s !== undefined ? (((s as any) instanceof Number) ? +s : parseInt(s as string)) : (def !== undefined ? def : 0)
  } catch (error) {
    logger.error('Unable to convert the environment variable value to a number: %s', s);
    throw new Error(`Unable to convert the environment variable value to a number: '${s}'`)
  }
}
```

Now, in the code above, particularly within `logging.ts` inside of `initializeLogger`, the second file transport that is setup is formatted using the `StandardUnstructuredFormat` formatter, which is a semi-
structured plain-text format, i.e. _not_ JSON. Despite wanting to send my logging data to New Relic to
light up the "logs in context" feature, I _still_ want to log to disk using a plain-text format. But the
New Relic NodeJS agent completely stomps on my logger's formatting by overriding my logger format. 😢 Not cool.

## Your Environment

Browser name and version: N/A
Node version: 14.17.0 and 16.15.0
OS: Windows Server 2019 (17763.2931)

**Comment by bizob2828** [comment]
@fourpastmidnight which version of the agent are you on?  We got this report last week and have since fixed in [8.11.2](https://github.com/newrelic/node-newrelic/releases/tag/v8.11.2)

**Comment by fourpastmidnight** [comment]
Oh, hmm, well now, 8.11.1. No sooner than I had implemented my first go-round of this, and I see that 8.11.2 was released, like, yesterday or something! 😄  THe web moves too fast!!! I'll update and report back if I still have an issue.

**Comment by fourpastmidnight** [comment]
OK, v8.11.2 "fixes" the JSON formatting issue. But, there's still another issue: you guys overwrite _any_ timestamp attribute for all transports/sinks. I'll open another issue for that.
